name: polkawallet_plugin_acala
description: Acala network plugin for polkawallet.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: any
  mobx: any
  flutter_mobx: any
  json_annotation: any
  flutter_svg: any
  get_storage: any
  device_info: any
  polkawallet_sdk: any
#  polkawallet_sdk:
#    path: ../sdk
  polkawallet_ui:
    git:
      url: https://github.com/polkawallet-io/ui.git
      ref: 225debc79aa5e3aca6783a3506bcc3e596398e7c
#    path: ../ui

dev_dependencies:
  build_runner: ^1.10.11
  mobx_codegen: ^1.1.1
  json_serializable: ^3.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - lib/js_service_acala/dist/main.js
    - assets/images/logo.png
    - assets/images/logo_gray.png
    - assets/images/acala_indigo.png
    - assets/images/acala_dark.png
    - assets/images/assets_up.png
    - assets/images/assets_down.png
    - assets/images/assets_send.png
    - assets/images/swap.svg
    - assets/images/exchange.svg
    - assets/images/loan.svg
    - assets/images/loan-start.svg
    - assets/images/deposit.svg
    - assets/images/scan.svg
    - assets/images/faucet.svg
    - assets/images/nft.svg
    - assets/images/tokens/ACA.png
    - assets/images/tokens/AUSD.png
    - assets/images/tokens/DOT.png
    - assets/images/tokens/LDOT.png
    - assets/images/tokens/RENBTC.png
    - assets/images/tokens/XBTC.png

  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
